export const API_PATHS = {
  AUTH: {
    REGISTER: '/api/auth/register',
    LOGIN: '/api/auth/login',
    SELECT_ROLE: '/api/auth/select-role',
    SWITCH_ROLE: '/api/auth/switch-role',
    LOGOUT: '/api/auth/logout',
    GET_ME: '/api/auth/me',
    UPDATE_PROFILE: '/api/auth/profile',
    UPLOAD_AVATAR: '/api/auth/avatar',
    CHANGE_PASSWORD: '/api/auth/change-password',
  },
  SHOP: {
    CREATE: '/api/shops',
    GET_ALL: '/api/shops',
    GET_MY_SHOP: '/api/shops/my',
    GET_ONE: (id) => `/api/shops/${id}`,
    UPDATE: (id) => `/api/shops/${id}`,
    QUEUE_INFO: (id) => `/api/shops/${id}/queue`,
    UPLOAD_PHOTOS: '/api/shops/photos',
    DELETE_PHOTO: '/api/shops/photos',
  },
  BARBER: {
    ADD: (shopId) => `/api/shops/${shopId}/barbers`,
    GET_SHOP_BARBERS: (shopId) => `/api/shops/${shopId}/barbers`,
    UPDATE: (id) => `/api/barbers/${id}`,
    DELETE: (id) => `/api/barbers/${id}`,
    LOOKUP_USER: '/api/barbers/lookup-user',
    GET_PROFILE: '/api/barber/profile',
    TOGGLE_AVAILABILITY: '/api/barber/availability',
    SET_DELAY: '/api/barber/delay',
  },
  SERVICE: {
    ADD: (shopId) => `/api/shops/${shopId}/services`,
    GET_SHOP_SERVICES: (shopId) => `/api/shops/${shopId}/services`,
    UPDATE: (id) => `/api/services/${id}`,
    DELETE: (id) => `/api/services/${id}`,
  },
  APPOINTMENT: {
    BOOK: '/api/appointments',
    MY_APPOINTMENTS: '/api/appointments/my',
    GET_ONE: (id) => `/api/appointments/${id}`,
    CANCEL: (id) => `/api/appointments/${id}/cancel`,
    START: (id) => `/api/barber/appointments/${id}/start`,
    COMPLETE: (id) => `/api/barber/appointments/${id}/complete`,
    APPROVE: (id) => `/api/barber/appointments/${id}/approve`,
    REJECT: (id) => `/api/barber/appointments/${id}/reject`,
    NO_SHOW: (id) => `/api/barber/appointments/${id}/no-show`,
    BARBER_QUEUE: '/api/barber/queue',
    BARBER_APPOINTMENTS: '/api/barber/appointments',
    WALK_IN: '/api/barber/walk-in',
    SHOP_APPOINTMENTS: (shopId) => `/api/shops/${shopId}/appointments`,
  },
  REVIEW: {
    SUBMIT: '/api/reviews',
    CHECK: '/api/reviews/check',
    MY_REVIEWS: '/api/reviews/my',
    MY_BARBER_REVIEWS: '/api/reviews/my-barber',
    SHOP_REVIEWS: (shopId) => `/api/reviews/shop/${shopId}`,
    BARBER_REVIEWS: (barberId) => `/api/reviews/barber/${barberId}`,
  },
  ADMIN: {
    PENDING_SHOPS: '/api/admin/shops/pending',
    APPROVED_SHOPS: '/api/admin/shops/approved',
    REJECTED_SHOPS: '/api/admin/shops/rejected',
    SHOP_DETAILS: (id) => `/api/admin/shops/${id}/details`,
    APPROVE_SHOP: (id) => `/api/admin/shops/${id}/approve`,
    REJECT_SHOP: (id) => `/api/admin/shops/${id}/reject`,
    TOGGLE_SHOP_STATUS: (id) => `/api/admin/shops/${id}/status`,
    DELETE_SHOP: (id) => `/api/admin/shops/${id}`,
    MANAGERS: '/api/admin/managers',
    CREATE_MANAGER: '/api/admin/managers',
    UPDATE_MANAGER: (id) => `/api/admin/managers/${id}`,
    TOGGLE_MANAGER_STATUS: (id) => `/api/admin/managers/${id}/status`,
    DELETE_MANAGER: (id) => `/api/admin/managers/${id}`,
  },
};
